db.transportadora.insertMany([
{_id: 1,  nombre: 'Domesa',  tipoServicio: 'Paquetería',  origen: 'Ipiales', destino: 'Pasto', fechaEnvio: "2024-01-10", fechaEntrega: "2024-01-11",  costo: 22000,  estado: 'En tránsito',  descripcion: 'Pasaportes', TipoTransporte: 'aéreo'},
  {_id: 2,  nombre: 'Domesa',  tipoServicio: 'Paquetería',  origen: 'Ipiales',  destino: 'Pasto',  fechaEnvio: "2024-02-15",  fechaEntrega: "2024-02-20", costo: 150000, estado: 'Pendiente',  descripcion: 'Pasaportes',TipoTransporte: 'terrestre'},
  {_id: 3,  nombre: 'Domesa', tipoServicio: 'Logística',  origen: 'Ipiales', destino: 'Pasto', fechaEnvio: "2024-03-05", fechaEntrega: "2024-03-07", costo: 75000, estado: 'Entregado', escripcion: 'Pasaportes',TipoTransporte: 'terrestre'},
  {_id: 4, nombre: 'BY TREND',  tipoServicio: 'Carga',  origen: 'Bogotá',  destino: 'Ibagué',  fechaEnvio: "2024-04-12",  fechaEntrega: "2024-04-15", costo: 200000, estado: 'En tránsito', descripcion: 'Dulces exportados',TipoTransporte: 'aéreo' },
  {_id: 5,  nombre: 'BY TREND',  tipoServicio: 'Paquetería',  origen: 'Bogotá',  destino: 'Ibagué',  fechaEnvio: "2024-05-20",  fechaEntrega: "2024-05-21",  costo: 30000, estado: 'Entregado', descripcion: 'Dulces exportados',TipoTransporte: 'terrestre'},
  {_id: 6,  nombre: 'BY TREND',  tipoServicio: 'Logística',  origen: 'Bogotá',  destino: 'Ibagué', fechaEnvio: "2024-06-10", fechaEntrega: "2024-06-12", costo: 85000,  estado: 'Pendiente', descripcion: 'Dulces exportados',TipoTransporte: 'aéreo'},
  {_id: 7, nombre: 'Berlimotos',  tipoServicio: 'Carga',  origen: 'Cali',  destino: 'Bogotá',  fechaEnvio: "2024-07-18",  fechaEntrega: "2024-07-22",  costo: 120000,   estado: 'En tránsito', descripcion: 'Repuestos moto',TipoTransporte: 'terrestre'},
  {_id: 8, nombre: 'Berlimotos', tipoServicio: 'Logística',  origen: 'Cali',  destino: 'Bogotá',  fechaEnvio: "2024-08-25",  fechaEntrega: "2024-08-27", costo: 65000, estado: 'Entregado',  descripcion: 'Repuestos moto',TipoTransporte: 'aéreo'},
  {_id: 9, nombre: 'Berlimotos ',  tipoServicio: 'Paquetería',  origen: 'Cali',  destino: 'Bogotá',  fechaEnvio: "2024-09-05",  fechaEntrega: "2024-09-07", costo: 40000,  estado: 'Pendiente',  descripcion: 'Repuestos moto',TipoTransporte: 'terrestre'},
  {_id: 10, nombre: 'Las Palmas',  tipoServicio: 'Carga',  origen: 'Medellin',  destino: 'Villavicencio',  fechaEnvio: "2024-10-10",  fechaEntrega: "2024-10-15",  costo: 180000,  estado: 'En tránsito', descripcion: 'Papeleria',TipoTransporte: 'aéreo'},
  {_id: 11, nombre: 'Las Palmas', tipoServicio: 'Logística', origen: 'Medellin', destino: 'Cali', fechaEnvio: "2024-11-12", fechaEntrega: "2024-11-14",  costo: 90000,  estado: 'Entregado', descripcion: 'Papeleria',TipoTransporte: 'terrestre'},
  {_id: 12,  nombre: 'Las Palmas',  tipoServicio: 'Carga',  origen: 'Medellin',  destino: 'Cali',  fechaEnvio: "2024-12-01",  fechaEntrega: "2024-12-03", costo: 110000, estado: 'Pendiente',  descripcion: 'Papeleria',TipoTransporte: 'aéreo'},
  {_id: 13,   nombre: 'La Cali',   tipoServicio: 'Paquetería',    origen: 'Manizales',    destino: 'Cali',    fechaEnvio: "2024-01-15",    fechaEntrega: "2024-01-16",  costo: 35000, estado: 'Entregado',  descripcion: 'Cacharreria',TipoTransporte: 'aéreo'},
  {_id: 14,  nombre: 'La Cali',  tipoServicio: 'Logística',  origen: 'Manizales',  destino: 'Medellin',  fechaEnvio: "2024-02-20",  fechaEntrega: "2024-02-22", costo: 80000, estado: 'En tránsito',  descripcion: 'Cacharreria',TipoTransporte: 'terrestre'},
  {_id: 15,  nombre: 'La Cali',  tipoServicio: 'Carga',  origen: 'Manizales',  destino: 'Medellin',  fechaEnvio: "2024-03-10",  fechaEntrega: "2024-03-14",  costo: 160000, estado: 'En tránsito',  descripcion: 'Cacharreria',TipoTransporte: 'aéreo'},
  {_id: 16,   nombre: 'La Pastusita',   tipoServicio: 'Logística',   origen: 'Pereira',   destino: 'Manizales',   fechaEnvio: "2024-04-18",   fechaEntrega: "2024-04-20", costo: 95000, estado: 'Pendiente', descripcion: 'Maquillaje' ,TipoTransporte: 'aéreo'},
  {_id: 17, nombre: 'La Pastusita',  tipoServicio: 'Paquetería',  origen: 'Pereira',  destino: 'Manizales',  fechaEnvio: "2024-05-25",  fechaEntrega: "2024-05-26", costo: 45000, estado: 'Entregado', descripcion: 'Maquillaje',TipoTransporte: 'terrestre'},
  {_id: 18, nombre: 'La Pastusita',  tipoServicio: 'Logística',  origen: 'Pereira',  destino: 'Manizales',  fechaEnvio: "2024-06-05",  fechaEntrega: "2024-06-07",  costo: 70000,  estado: 'En tránsito',   descripcion: 'Maquillaje' ,TipoTransporte: 'aéreo'},
  {_id: 19,  nombre: 'ModaFem',  tipoServicio: 'Carga',  origen: 'Cartagena',  destino: 'Pereira',  fechaEnvio: "2024-07-12",  fechaEntrega: "2024-07-16", costo: 170000, estado: 'Pendiente',  descripcion: 'Ropa femenina',TipoTransporte: 'terrestre'},
  {_id: 20, nombre: 'ModaFem', tipoServicio: 'Paquetería', origen: 'Cartagena', destino: 'Pereira',  fechaEnvio: "2024-08-20",  fechaEntrega: "2024-08-21",  costo: 40000, estado: 'Entregado',  descripcion: 'Ropa femenina',TipoTransporte: 'aéreo'},
  {_id: 21,  nombre: 'ModaFem',  tipoServicio: 'Logística',  origen: 'Cartagena',   destino: 'Pereira',   fechaEnvio: "2024-09-10",   fechaEntrega: "2024-09-12", costo: 85000,  estado: 'En tránsito',  descripcion: 'Ropa femenina',TipoTransporte: 'terrestre'},
  {_id: 22,  nombre: 'Quimicos la 21',  tipoServicio: 'Carga',  origen: 'Villavicencio',  destino: 'Cartagena',  fechaEnvio: "2024-10-15",  fechaEntrega: "2024-10-19",  costo: 130000, estado: 'Pendiente', descripcion: 'Medicamentos naturales',TipoTransporte: 'aéreo' },
  {_id: 23, nombre: 'Quimicos la 21',  tipoServicio: 'Paquetería',  origen: 'Villavicencio',  destino: 'Cartagena',  fechaEnvio: "2024-11-05",  fechaEntrega: "2024-11-06",  costo: 38000, estado: 'Entregado', descripcion: 'Medicamentos naturales',TipoTransporte: 'terrestre' },
  {_id: 24,  nombre: 'Quimicos la 21',  tipoServicio: 'Logística',  origen: 'Villavicencio',  destino: 'Cartagena',  fechaEnvio: "2024-12-20",  fechaEntrega: "2024-12-22",   costo: 90000, estado: 'En tránsito', descripcion: 'Medicamentos naturales',TipoTransporte: 'aéreo' },
  {_id: 25, nombre: 'Unicentro', tipoServicio: 'Carga', origen: 'Bogotá',  destino: 'Villavicencio',  fechaEnvio: "2024-01-08",  fechaEntrega: "2024-01-13", costo: 140000,  estado: 'Pendiente', descripcion: 'Juguetes',TipoTransporte: 'terrestre'},
  {_id: 26,  nombre: 'Unicentro',  tipoServicio: 'Paquetería',  origen: 'Tumaco',  destino: 'Villavicencio',   fechaEnvio: "2024-02-18",   fechaEntrega: "2024-02-19",  costo: 42000,   estado: 'Entregado',  descripcion: 'Juguetes',TipoTransporte: 'aéreo' },
  {_id: 27,  nombre: 'Unicentro',  tipoServicio: 'Logística',  origen: 'Tumaco',  destino: 'Villavicencio',  fechaEnvio: "2024-03-25",  fechaEntrega: "2024-03-27",  costo: 95000,  estado: 'En tránsito',   descripcion: 'Juguetes' ,TipoTransporte: 'terrestre'},
  {_id: 28,  nombre: 'Deportes al día',  tipoServicio: 'Carga',  origen: 'Barranquilla',  destino: 'Tumaco',  fechaEnvio: "2024-04-10",  fechaEntrega: "2024-04-14",  costo: 160000, estado: 'Pendiente',  descripcion: 'Ropa deportiva',TipoTransporte: 'aéreo' },
  {_id: 29, nombre: 'Deportes al día',  tipoServicio: 'Paquetería',  origen: 'Barranquilla',  destino: 'Tumaco',  fechaEnvio: "2024-05-22",  fechaEntrega: "2024-05-23",  costo: 39000, estado: 'Entregado', descripcion: 'Ropa deportiva',TipoTransporte: 'terrestre' },
  {_id: 30,   nombre: 'Deportes al día', tipoServicio: 'Logística', origen: 'Barranquilla', destino: 'Tumaco',  fechaEnvio: "2024-06-30",  fechaEntrega: "2024-07-02", costo: 80000, estado: 'En tránsito',  descripcion: 'Ropa deportiva',TipoTransporte: 'aéreo' },
  {_id: 31, nombre: 'Alkosto', tipoServicio: 'Carga', origen: 'Cúcuta', destino: 'Barranquilla',  fechaEnvio: "2024-07-15",  fechaEntrega: "2024-07-20",  costo: 175000, estado: 'Pendiente',  descripcion: 'Tecnología' ,TipoTransporte: 'terrestre'},
  {_id: 32, nombre: 'Alkosto',  tipoServicio: 'Paquetería',  origen: 'Bucaramanga',  destino: 'Barranquilla',  fechaEnvio: "2024-08-05", fechaEntrega: "2024-08-06", costo: 36000, estado: 'Entregado', descripcion: 'Tecnología',TipoTransporte: 'aéreo',TipoTransporte: 'terrestre'},
  {_id: 33,  nombre: 'Alkosto',  tipoServicio: 'Logística',  origen: 'Bucaramanga',  destino: 'Barranquilla',  fechaEnvio: "2024-09-12",  fechaEntrega: "2024-09-14",  costo: 92000,  estado: 'En tránsito', descripcion: 'Tecnología',TipoTransporte: 'terrestre'},
  {_id: 34,  nombre: 'solo fruta',  tipoServicio: 'Carga',  origen: 'Norte de Santander',  destino: 'Bucaramanga',  fechaEnvio: "2024-10-20",  fechaEntrega: "2024-10-24",  costo: 145000, estado: 'Pendiente', descripcion: 'instrumentos de cocina',TipoTransporte: 'aéreo'},
  {_id: 35,  nombre: 'solo fruta',  tipoServicio: 'Logística',  origen: 'Norte de Santander',  destino: 'Bucaramanga',  fechaEnvio: "2024-11-08",  fechaEntrega:"2024-11-10",  costo: 87000, estado: 'Entregado',  descripcion: 'instrumentos de cocina',TipoTransporte: 'terrestre'},
  {_id: 36,  nombre: 'solo fruta',  tipoServicio: 'Paquetería',  origen: 'Norte de Santander',  destino: 'Bucaramanga',  fechaEnvio: "2024-12-18",  fechaEntrega: "2024-12-19",  costo: 43000, estado: 'En tránsito',  descripcion: 'instrumentos de cocina',TipoTransporte: 'aéreo'},
  {_id: 37,   nombre: 'Tienda Mug',   tipoServicio: 'Logística',  origen: 'Nariño',  destino: 'Norte de Santander',  fechaEnvio: "2024-01-25",  fechaEntrega: "2024-01-27", costo: 88000,  estado: 'Pendiente',  descripcion: 'Regalos' ,TipoTransporte: 'terrestre'},
  {_id: 38, nombre: 'Tienda Mug', tipoServicio: 'Carga', origen: 'Nariño', destino: 'Norte de Santander',  fechaEnvio: "2024-02-10",  fechaEntrega: "2024-02-15",  costo: 150000, estado: 'Entregado',  descripcion: 'Regalos',TipoTransporte: 'aéreo'},
  {_id: 39, nombre: 'Tienda Mug',  tipoServicio: 'Paquetería',  origen: 'Nariño',  destino: 'Norte de Santander',  fechaEnvio: "2024-03-18",  fechaEntrega: "2024-03-19", costo: 37000, estado: 'En tránsito', descripcion: 'Regalos' ,TipoTransporte: 'terrestre'},
  {_id: 40,  nombre: 'Milhoja',  tipoServicio: 'Logística',  origen: 'Arauca',  destino: 'Nariño',  fechaEnvio: "2024-04-25",  fechaEntrega: "2024-04-27", costo: 93000, estado: 'Pendiente',  descripcion: 'Desechables',TipoTransporte: 'aéreo'},
  {_id: 41, nombre: 'Milhoja', tipoServicio: 'Carga', origen: 'Arauca', destino: 'Nariño', fechaEnvio: "2024-05-10", fechaEntrega: "2024-05-14", costo: 135000, estado: 'Entregado', descripcion: 'Desechables',TipoTransporte: 'terrestre'},
  {_id: 42, nombre: 'Valladolid', tipoServicio: 'Paquetería', origen: 'Arauca', destino: 'Nariño', fechaEnvio: "2024-06-18", fechaEntrega: "2024-06-19", costo: 44000, estado: 'En tránsito', descripcion: 'Desechables',TipoTransporte: 'aéreo'},
  {_id: 43,  nombre: 'Valladolid',  tipoServicio: 'Logística',  origen: 'Riohacha',  destino: 'Arauca',  fechaEnvio: "2024-07-22",  fechaEntrega: "2024-07-24",  costo: 96000,  estado: 'Pendiente', descripcion: 'Andamios',TipoTransporte: 'terrestre' },
  {_id: 44,  nombre: 'Valladolid',  tipoServicio: 'Carga',  origen: 'Riohacha',  destino: 'Arauca',  fechaEnvio: "2024-08-05",  fechaEntrega: "2024-08-09", costo: 155000,  estado: 'Entregado',  descripcion: 'Andamios',TipoTransporte: 'aéreo'},
  {_id: 45,  nombre: 'clinica fatima',  tipoServicio: 'Paquetería',  origen: 'Riohacha',  destino: 'Arauca',  fechaEnvio: "2024-09-15",  fechaEntrega: "2024-09-16", costo: 40000, estado: 'En tránsito',  descripcion: 'Correspondencia' ,TipoTransporte: 'terrestre'},
  {_id: 46, nombre: 'clinica fatima', tipoServicio: 'Logística',  origen: 'Montería',   destino: 'Riohacha',  fechaEnvio: "2024-10-20",  fechaEntrega: "2024-10-22",  costo: 92000, estado: 'Pendiente',  descripcion: 'Correspondencia',TipoTransporte: 'aéreo'},
  {_id: 47, nombre: 'clinica fatima', tipoServicio: 'Logística', origen: 'Montería', destino: 'Riohacha', fechaEnvio: "2024-11-12", fechaEntrega: "2024-11-14", costo: 89000, estado: 'Entregado', descripcion: 'Correspondencia',TipoTransporte: 'terrestre'},
  {_id: 48,  nombre: 'Valle de Atriz',  tipoServicio: 'Carga',  origen: 'Montería',  destino: 'Riohacha',  fechaEnvio: "2024-12-18",  fechaEntrega: "2024-12-23",  costo: 165000, estado: 'En tránsito', descripcion: 'Medicamentos',TipoTransporte: 'aéreo'},
  {_id: 49,  nombre: 'Valle de Atriz',  tipoServicio: 'Paquetería',  origen: 'Ibagué', destino: 'Montería', fechaEnvio: "2024-01-05", fechaEntrega: "2024-01-06", costo: 36000, estado: 'Pendiente', descripcion: 'Medicamentos',TipoTransporte: 'terrestre'},
  {_id: 50,  nombre: 'Valle de Atriz',  tipoServicio: 'Logística',  origen: 'Ibagué',  destino: 'Montería',  fechaEnvio: "2024-02-22",  fechaEntrega: "2024-02-24", costo: 98000, estado: 'Entregado', descripcion: 'Medicamentos',TipoTransporte: 'aéreo'}]);

db.transportadora.find().skip(20).limit(30).toArray()




    



